site_name: 嘉树 Jiashu's Blog
site_url: https://aka-jiashu.online/blog/
site_dir: dist/blog

theme:
  name: material
  language: zh
  custom_dir: docs/overrides
  features:
    - content.code.copy
  icon:
    logo: material/leaf
  comments:
    provider: giscus
  palette:
    - scheme: default
      primary: teal
      accent: teal

nav:
  - 博客: index.md
  - 标签: tags.md
  - 返回首页: https://aka-jiashu.online/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

plugins:
  - group:
      enabled: true
      plugins:
        - blog:
            blog_dir: .
            post_dir: posts
            archive: true
            categories: true
        - offline
        - social
        - tags
        - search:
            lang: ['en', 'zh']

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/mermaid.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

extra:
  giscus:
    repo: aka-jiashu/Jiashu-Homepage
    repo_id: R_kgDOQceRXA
    category: General
    category_id: DIC_kwDOQceRXM4C2e7w
    mapping: pathname
    strict: 0
    reactions_enabled: 1
    emit_metadata: 0
    input_position: bottom
    theme: preferred_color_scheme
    lang: zh-CN
